/**
 * Generated by Lovrabet CLI
 * Created: 2025-10-11T05:47:17.236Z
 *
 * 这个文件包含了项目的模型配置，并自动注册到 SDK 中
 * CLI 工具会自动维护这个文件，通常不需要手动修改
 */

import { registerModels, type ModelsConfig } from "@lovrabet/sdk";
export const ACCESS_KEY = process.env.ACCESS_KEY;
export const LOVRABET_APP_CODE = process.env.NEXT_PUBLIC_APP_CODE || "";
/**
 * 项目的模型配置
 * 包含所有数据表的映射关系
 */
export const LOVRABET_MODELS_CONFIG: ModelsConfig = {
  appCode: LOVRABET_APP_CODE,
  models: {
    Suppliers: {
      tableName: "suppliers",
      datasetCode: "3cc328a56a79432f9796d45f61688c6d",
    },
    PurchaseOrders: {
      tableName: "purchase_orders",
      datasetCode: "83123ed76bd246f19385ded2678a579b",
    },
    PaymentRecords: {
      tableName: "payment_records",
      datasetCode: "1438ed567dc1443fb6aea7c3921272ae",
    },
    OrderItems: {
      tableName: "order_items",
      datasetCode: "c88e5309206a409f9811c54966f8a510",
    },
    Contracts: {
      tableName: "contracts",
      datasetCode: "b013d9ba03f342b7b9f65d16f1ae7934",
    },
    Dataset71b764e9c6c94658a7949ad99d3575d1: {
      tableName: "dataset_71b764e9c6c94658a7949ad99d3575d1",
      datasetCode: "71b764e9c6c94658a7949ad99d3575d1",
    },
    Dataset90c811bd56524e418503c9b163893db4: {
      tableName: "dataset_90c811bd56524e418503c9b163893db4",
      datasetCode: "90c811bd56524e418503c9b163893db4",
    },
  },
} as const;

/**
 * 自动注册配置
 * 配置名称: "app-d31cb8fb"
 */
registerModels(LOVRABET_MODELS_CONFIG);

/**
 * 如果需要支持多项目或多环境，可以注册额外的配置：
 *
 * // 开发环境配置
 * registerModels({
 *   appCode: 'app-dev-123',
 *   models: { ... }
 * }, 'dev');
 *
 * // 其他项目配置
 * registerModels({
 *   appCode: 'other-project',
 *   models: { ... }
 * }, 'project-b');
 */
