/**
 * Generated by Lovrabet CLI
 * Created: 2025-09-28T03:44:26.903Z
 *
 * 这个文件包含了项目的模型配置，并自动注册到 SDK 中
 * CLI 工具会自动维护这个文件，通常不需要手动修改
 */

import { registerModels, CONFIG_NAMES, type ModelsConfig } from "@lovrabet/sdk";
export const ACCESS_KEY = "ak-xIXmgi99gwTqa4cwMXwe2wba_gN40dcuBvzFpDRbo_w"
export const LOVRABET_APP_CODE = "app-64289c49";
;
/**
 * 项目的模型配置
 * 包含所有数据表的映射关系
 */
export const LOVRABET_MODELS_CONFIG: ModelsConfig = {
  appCode: LOVRABET_APP_CODE,
  models: {
    Product: {
      tableName: "product",
      datasetCode: "cfac23c9d6ce42c0a8f66cc85df75b4b",
    },
    CustomerContact: {
      tableName: "customer_contact",
      datasetCode: "5717da5e8ce14515ae7bfc5c8277c33d",
    },
    CustomerLevel: {
      tableName: "customer_level",
      datasetCode: "0984287205234640a69a9b123af76542",
    },
    Customer: {
      tableName: "customer",
      datasetCode: "9fdfc7a5e0bb4c4bb48323ff676e74c5",
    },
    BizOpportunity: {
      tableName: "biz_opportunity",
      datasetCode: "249421053adf454cb56437609f9fc9fd",
    },
    OrderInfo: {
      tableName: "order_info",
      datasetCode: "e57aa233788c403c89d3a995800efc21",
    },
    D2Order: {
      tableName: "d2_order",
      datasetCode: "7068d3290eb141c5a3c8fafcaa65a7d9",
    },
    DatasetB2601e93bf0649538c513df93418b75f: {
      tableName: "dataset_b2601e93bf0649538c513df93418b75f",
      datasetCode: "b2601e93bf0649538c513df93418b75f",
    },
  },
} as const;

/**
 * 自动注册配置
 * 配置名称: CONFIG_NAMES.DEFAULT
 */
registerModels(LOVRABET_MODELS_CONFIG, CONFIG_NAMES.DEFAULT);

/**
 * 如果需要支持多项目或多环境，可以注册额外的配置：
 *
 * // 开发环境配置
 * registerModels({
 *   appCode: 'app-dev-123',
 *   models: { ... }
 * }, 'dev');
 *
 * // 其他项目配置
 * registerModels({
 *   appCode: 'other-project',
 *   models: { ... }
 * }, 'project-b');
 */
