/**
 * Generated by Lovrabet CLI
 * Created: 2025-10-09T06:51:49.274Z
 *
 * 这个文件包含了项目的模型配置，并自动注册到 SDK 中
 * CLI 工具会自动维护这个文件，通常不需要手动修改
 */

import { registerModels, type ModelsConfig } from "@lovrabet/sdk";
export const ACCESS_KEY = "ak-KgyJkUVrtKB5ewfRkfvhZcYwKFGpqzI0kvDWv7I4GS0";
export const LOVRABET_APP_CODE = "app-c4055413";

/**
 * 项目的模型配置
 * 包含所有数据表的映射关系
 */
export const LOVRABET_MODELS_CONFIG: ModelsConfig = {
  appCode: LOVRABET_APP_CODE,
  models: {
    XhzdSurnfu: {
      tableName: "xhzd_surnfu",
      datasetCode: "bd3b2051697a42f3b3f6bb2201909d6b",
    },
    WordDetail: {
      tableName: "word_detail",
      datasetCode: "fe58742581ba42ccb14d292d56838fe5",
    },
    UsersInfo: {
      tableName: "users_info",
      datasetCode: "f8afbe3f6f12438dac556ebb3ae2c9cf",
    },
    UserStats: {
      tableName: "user_stats",
      datasetCode: "4f40c35ae9924a30a7aa6ba20dadc8ba",
    },
    UserPlanChars: {
      tableName: "user_plan_chars",
      datasetCode: "4fc4048aa1934baf8a60aec594fd51d5",
    },
    UserPlan: {
      tableName: "user_plan",
      datasetCode: "5f84fe1ada58489394b6ec5e6f99cbb4",
    },
    UserMastery: {
      tableName: "user_mastery",
      datasetCode: "2738d6436a58433e90806559a0779dfd",
    },
    UserAssessment: {
      tableName: "user_assessment",
      datasetCode: "c1191a60faf14f34bef0456b13903e50",
    },
    Topic: {
      tableName: "topic",
      datasetCode: "ef8aa6d530e24f9b83513c25a802e2c3",
    },
    TextbookPhrases: {
      tableName: "textbook_phrases",
      datasetCode: "76a873945291498498737bc85677983d",
    },
    TextbookCharacters: {
      tableName: "textbook_characters",
      datasetCode: "7786dc8d11124b5c947c1a205fade8b2",
    },
    SimilarChars: {
      tableName: "similar_chars",
      datasetCode: "035867df60094d9da6f40215fdeaf645",
    },
    PlanAssessment: {
      tableName: "plan_assessment",
      datasetCode: "c8f6b67804894cd9917f916e1545f85a",
    },
    PinyinTestRecords: {
      tableName: "pinyin_test_records",
      datasetCode: "62e5f0c4ebdd49d79c3e48ca53d78b58",
    },
    PinyinTestQuestions: {
      tableName: "pinyin_test_questions",
      datasetCode: "c5d56073d74b41afb3dd625a8cfb83d1",
    },
    PhraseIdiomDefinitions: {
      tableName: "phrase_idiom_definitions",
      datasetCode: "237cd4299fd9495dbd990d3d1ac87d7d",
    },
    PhraseDetails: {
      tableName: "phrase_details",
      datasetCode: "5bddc619f79c4fb682f50ef1469f63ab",
    },
    PhraseDetailDefinitions: {
      tableName: "phrase_detail_definitions",
      datasetCode: "ff6f6e24d2aa4cf2ac47ccaa097c625f",
    },
    PhraseBasicDefinitions: {
      tableName: "phrase_basic_definitions",
      datasetCode: "4f4b991e49f14df7abf1065eff2ee5b4",
    },
    MatchingUserProgress: {
      tableName: "matching_user_progress",
      datasetCode: "1296e6b411c2468887a3ee41fff559ce",
    },
    MatchingUserHistory: {
      tableName: "matching_user_history",
      datasetCode: "e08946396a6a496f87e9d81636bf6259",
    },
    MatchingLevels: {
      tableName: "matching_levels",
      datasetCode: "8c33b88669fb4c6a986961fd73ec1ae2",
    },
    MatchingLevelChars: {
      tableName: "matching_level_chars",
      datasetCode: "01589081ce4d4d59818a5e9c134139de",
    },
    MasteryWords: {
      tableName: "mastery_words",
      datasetCode: "0ea6814ebb8841a9b9cd85933008a18e",
    },
    CharacterStrokes: {
      tableName: "character_strokes",
      datasetCode: "7b4c2be10c764ebd8eafa501dbd626fc",
    },
    CharacterPinyinDefinitions: {
      tableName: "character_pinyin_definitions",
      datasetCode: "45127e89b83345658ea322eaf3dae6cd",
    },
    CharacterDetails: {
      tableName: "character_details",
      datasetCode: "f3847284577c4ed6a356f4c9fe4d945a",
    },
    CharacterDetailDefinitions: {
      tableName: "character_detail_definitions",
      datasetCode: "3c22be96ff484499b86f073372b84440",
    },
    CharacterBasicDefinitions: {
      tableName: "character_basic_definitions",
      datasetCode: "9e72dede3c2f449f9649e6f291841cf0",
    },
    CharacterBase: {
      tableName: "character_base",
      datasetCode: "3881431210da4afe9987618d0d7bc454",
    },
    CharLearningLog: {
      tableName: "char_learning_log",
      datasetCode: "f87ff6f6525d4546b6e16d546521c262",
    },
    BasWord: {
      tableName: "bas_word",
      datasetCode: "664e507c9e5241158b3aa774d80659a6",
    },
    WordClass: {
      tableName: "word_class",
      datasetCode: "645d955f284549509dbb1822003d3c78",
    },
    TextbookEdition: {
      tableName: "textbook_edition",
      datasetCode: "9c43844ec35e42f5a69a4d1e13436583",
    },
    RadicalCharMapping: {
      tableName: "radical_char_mapping",
      datasetCode: "1f55358abd8249228f1ff2d0e9f1f702",
    },
    HsPinyin: {
      tableName: "hs_pinyin",
      datasetCode: "953ebf207ea642ca85d53469e2e084ef",
    },
    GradeInfo: {
      tableName: "grade_info",
      datasetCode: "aa49b86a9ce9432aae1b9317c54deee1",
    },
    DetailType: {
      tableName: "detail_type",
      datasetCode: "21d78c89645341d49cc9f178f8a805e3",
    },
    CharacterMapping: {
      tableName: "character_mapping",
      datasetCode: "26b0c038caed4bb7947efc610262d1c6",
    },
    DatasetB5ff5fbb70be4bd195924d07e6ddcdb7: {
      tableName: "dataset_b5ff5fbb70be4bd195924d07e6ddcdb7",
      datasetCode: "b5ff5fbb70be4bd195924d07e6ddcdb7",
    },
    Dataset6119a0cd580840f4b526a1598450e762: {
      tableName: "dataset_6119a0cd580840f4b526a1598450e762",
      datasetCode: "6119a0cd580840f4b526a1598450e762",
    },
    Dataset29589c22969548f087ec87b2d6d37ee6: {
      tableName: "dataset_29589c22969548f087ec87b2d6d37ee6",
      datasetCode: "29589c22969548f087ec87b2d6d37ee6",
    },
    DatasetA0173cf1221d4c2cab01b94e5750c341: {
      tableName: "dataset_a0173cf1221d4c2cab01b94e5750c341",
      datasetCode: "a0173cf1221d4c2cab01b94e5750c341",
    },
  },
} as const;

/**
 * 自动注册配置
 * 配置名称: "app-c4055413"
 */
registerModels(LOVRABET_MODELS_CONFIG);

/**
 * 如果需要支持多项目或多环境，可以注册额外的配置：
 *
 * // 开发环境配置
 * registerModels({
 *   appCode: 'app-dev-123',
 *   models: { ... }
 * }, 'dev');
 *
 * // 其他项目配置
 * registerModels({
 *   appCode: 'other-project',
 *   models: { ... }
 * }, 'project-b');
 */
